name: AutoUpdateTransAndComits

on : push

jobs:
  updatetransdata:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - name: SetupPython
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: InstallLibrary
        run: pip install openpyxl
      - name: UpdateTransAndHatData
        run: python update_hat_data.py
      - name: GetAllChangeFiles
        id: changed-files
        uses: tj-actions/changed-files@v10.1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: AutoComit Update:trans data
      - name: UpdateTransDataComitHash
        uses: jossef/action-set-json-field@v1
        with:
          file: hat/hatData.json
          field: updateComitHash
          value: ${{ steps.auto-commit-action.outputs.commit_hash }}
      - name: UpdateTransDataComitHash
        run: python feat_comit_hash.py ${{ steps.auto-commit-action.outputs.commit_hash }} ${{ steps.changed-files.outputs.all_changed_files }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: AutoComit feat:comit hashs
